### ISSUE TITLE
Support phoenix channels (websockets) documentation

### ISSUE THREAD

**Issue by arnodirlam** [api-hogs/bureaucrat#14]
I think bureaucrat could be great for documenting phoenix channel messages and broadcasts, in addition to the API requests and responses it already supports. I'm not sure if it makes sense to support websockets without phoenix, but in any case phoenix could be an optional dependency.

The simplest and most common use cases for now, from my perspective, would be the ones described in the [phoenix channel docs](https://hexdocs.pm/phoenix/1.2.1/Phoenix.ChannelTest.html):

### Use Cases

1. **Connecting** a socket, with reply (:ok/:error)
  `connect(UserSocket, %{"some" => "params"})`
2. **Joining** a channel, with reply (:ok/:error, optional reply body)
  `subscribe_and_join(RoomChannel, "room:lobby", %{"id" => 3})`
3. Pushing a **message from client** to server, with reply (:ok/:error, optional reply body)
  `push socket, "my_event", %{"some" => "data"}`
4. **Broadcasting from client** to server (no reply)
  `broadcast_from socket, "my_event", %{"some" => "data"}`
5. Pushing a **message from server** to client (no reply)
  `assert_push "my_event", %{"some" => "data"}`
6. **Broadcasting from server** to client (no reply)
  `assert_broadcast "my_event", %{"some" => "data"}`

I guess 1. - 4. are close to what bureaucrat records already.
For 5. - 6. it would be good to filter according to what's asserted, so you filter out the "noise" such as presence_diff broadcasts when you don't need them. Instead of going through assert, this could possibly be done with an alias function such as `doc_assert` or so.

Would that be within the scope of bureaucrat for you?
Do you see any low-hanging fruits here?

**Comment by OpakAlex** [comment]
Hello @arnodirlam. Looks so interesting. IT will be good to have docs for channels, i agree this point with you. Do you want try start doing this?

**Comment by arnodirlam** [comment]
Great! I'll have a closer look until next week and keep you updated!

**Comment by arnodirlam** [comment]
Small update: Use cases 3.-6. are implemented and merged, use cases 1.-2. are yet to come (see below)

### Use Cases

1. **Connecting** a socket, with reply (:ok/:error)
  `connect(UserSocket, %{"some" => "params"})`
2. **Joining** a channel, with reply (:ok/:error, optional reply body)
  `subscribe_and_join(RoomChannel, "room:lobby", %{"id" => 3})`
