### ISSUE TITLE
README part for Swagger Integration

### ISSUE THREAD

**Issue by arnodirlam** [api-hogs/bureaucrat#15]
Swagger Integration was added by @mbuhot in #9 but not documentated yet in the README.

To help people who want to use it, improve popularity of bureaucrat, and to be able to continue development, this should be added.

**Comment by mbuhot** [comment]
Thanks for the reminder @arnodirlam, I can send a PR for a readme update soon.

> and to be able to continue development

Should we add an `examples/` directory to bureaucrat with a working phoenix project, swagger spec and bureaucrat output?

It wouldn't need to be part of the hex package, just something we can use for testing purposes.
Something like: https://github.com/mbuhot/phoenix_swagger/tree/swagger-ui/examples/simple

**Comment by arnodirlam** [comment]
Alright, great!

Having an example app would be awesome. Either within an examples folder in the same repo, as you suggested, or in a separate repo that's linked to in the README, like [distillery](https://github.com/bitwalker/distillery) does with [distillery-test](https://github.com/bitwalker/distillery-test). I'm leaning slightly towards a separate repo, because it reduces the "burden" of having to keep the example app up-to-date, but I'm fine with both :)

For ExUnit tests, I think it should be easy to create integration tests like this:
- start the bureaucrat application with a given config
- feed the recorder some `Plug.Conn` and optionally `Phoenix.Socket.*` structs
- call a writer
- run assertions on the output file, or even "mock" a file in memory (also to run in parallel)

As far as I understand, the swagger config is added to the app config directly? Then we probably wouldn't even need a fixture file of it for tests? So I guess we wouldn't need the example app within the repo for automated tests either.

**Comment by arnodirlam** [comment]
Thanks a lot @mbuhot 👍
