### ISSUE TITLE
Support phoenix 1.3

### ISSUE THREAD

**Issue by sergey-chechaev** [api-hogs/bureaucrat#22]

**Comment by OpakAlex** [comment]
Good for start oss @sergey-chechaev . PR are welcome!

**Comment by mbuhot** [comment]
@sergey-chechaev Have you tried using phoenix 1.3 with bureaucrat?
If you can be a bit more specific about what didn't work then I'm happy to assist.

**Comment by sergey-chechaev** [comment]
@mbuhot when i try generate the documentation file i have error:
```
19:10:11.046 [error] GenEvent handler Bureaucrat.Formatter installed in #PID<0.696.0> terminating
** (MatchError) no match of right hand side value: {:error, :enoent}
    (bureaucrat) lib/bureaucrat/markdown_writer.ex:3: Bureaucrat.MarkdownWriter.write/2
    (elixir) lib/enum.ex:1233: anonymous fn/3 in Enum.map/2
    (stdlib) lists.erl:1263: :lists.foldl/3
    (elixir) lib/enum.ex:1772: Enum.map/2
    (bureaucrat) lib/bureaucrat/formatter.ex:10: Bureaucrat.Formatter.handle_event/2
    (stdlib) gen_event.erl:533: :gen_event.server_update/4
    (stdlib) gen_event.erl:515: :gen_event.server_notify/4
    (stdlib) gen_event.erl:256: :gen_event.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:suite_finished, 522331, nil}
```

**Comment by sergey-chechaev** [comment]
@mbuhot error appears because of default_path. Phoenix 1.3 haven't folder web/controllers

**Comment by mbuhot** [comment]
Oh I see. That is already configurable as per https://github.com/api-hogs/bureaucrat#configuration

Once phoenix 1.3 is out of release-candidate status it probably makes sense to change the default path to not be `/web/controllers`.

On my projects the docs go to a `/doc` directory, but maybe a sensible default would just be the project root?
