### ISSUE TITLE
  The following arguments were given to Code.ensure_loaded?/1:

### ISSUE THREAD

**Issue by inderjit23** [api-hogs/bureaucrat#40]
hi i am getting this error 

my test-helper code
`Bureaucrat.start(
  env_var: "DOC",
  writer: Bureaucrat.SwaggerSlateMarkdownWriter,
  default_path: "doc/source/index.html.md",
  swagger: "priv/static/swagger.json"
           |> File.read!()
           |> Poison.decode!()
)

ExUnit.start(formatters: [ ExUnit.CLIFormatter,Bureaucrat.Formatter ])`

in conn case 
 import Bureaucrat.Helpers

** (FunctionClauseError) no function clause matching in Code.ensure_loaded?/1    
    
    The following arguments were given to Code.ensure_loaded?/1:
    
        # 1
        10
    
    Attempted function clauses (showing 1 out of 1):
    
        def ensure_loaded?(module) when is_atom(module)
    
    (elixir) lib/code.ex:869: Code.ensure_loaded?/1
    (ecto) lib/ecto/adapters/sql.ex:339: Ecto.Adapters.SQL.normalize_pool/1
    (elixir) lib/keyword.ex:831: Keyword.update/4
    (elixir) lib/keyword.ex:835: Keyword.update/4
    (ecto) lib/ecto/adapters/sql.ex:324: Ecto.Adapters.SQL.ensure_all_started/3
    (ecto) lib/mix/ecto.ex:99: Mix.Ecto.ensure_started/2
    (ecto) lib/mix/tasks/ecto.migrate.ex:76: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2

**Comment by OpakAlex** [comment]
And what this error means? What you think?
