### ISSUE TITLE
Support Elixir 1.7

### ISSUE THREAD

**Issue by bobics** [api-hogs/bureaucrat#41]
I don't know what's required for Elixir 1.7 support, but seeing this warning:

```
warning: the dependency :bureaucrat requires Elixir "~> 1.6.1" but you are running on v1.7.3
```

**Comment by OpakAlex** [comment]
it's warning. Does it works?

**Comment by bobics** [comment]
I'm seeing the following error when running `DOC=1 mix test`, with only a single **channel** test documented with `doc_push`. First time trying it out, so it's possible I'm doing something wrong as well:

```
12:02:00.691 [error] Task #PID<0.1354.0> started from #PID<0.90.0> terminating
** (stop) exited in: GenServer.stop(#PID<0.1365.0>, :normal, 30000)
    ** (EXIT) exited in: :sys.terminate(#PID<0.1365.0>, :normal, :infinity)
        ** (EXIT) an exception was raised:
            ** (MatchError) no match of right hand side value: {:error, :enoent}
                (bureaucrat) lib/bureaucrat/markdown_writer.ex:3: Bureaucrat.MarkdownWriter.write/2
```

**Comment by OpakAlex** [comment]
```
iex> File.read "unknown"
{:error, :enoent}
```
Looks like your code is wrong..

**Comment by bobics** [comment]
Thanks, I added configuration details to `Bureaucrat.start` and it fixed my issue. (It wasn't clear from the Bureaucrat readme I needed to specify configuration and I couldn't just do `Bureaucrat.start/0`).

```elixir
Bureaucrat.start(
 writer: Bureaucrat.MarkdownWriter,
 default_path: "API_README.md",
 paths: [],
 titles: [],
 env_var: "DOC"
)
```

I tried `doc_push` and `doc_broadcast_from!` and both seem to work.
