### ISSUE TITLE
Optional JSON library

### ISSUE THREAD

**Issue by lasseebert** [api-hogs/bureaucrat#43]
Now that Phoenix has moved to use Jason over Poison, it seems redundant to have multiple json libraries in one application.

Suggestion:
Make the json library configurable.

Something like

```elixir
config :bureaucrat, :json_library, Jason # Or Poison / others
```

This has been done in other hex packages too, so I think it should be doable :)

I will happily try to make a PR if the suggestion is approved.

**Comment by OpakAlex** [comment]
looks good, can you try to do a PR?

**Comment by lasseebert** [comment]
Will do :+1:
