### ISSUE TITLE
body_params is empty

### ISSUE THREAD

**Issue by pollingj** [api-hogs/bureaucrat#5]
Because I'm using `put_req_header` in my test `setup` and then passing the `conn` into the test the body_params is empty.  

Is there anyway around this at all?

**Comment by OpakAlex** [comment]
@romankuznietsov ?

**Comment by linjunpop** [comment]
I have met same issue, the `params` does have values, but not `body_params` and `query_params`, then I modified my test with

```diff
   test "creates and renders resource when data is valid", %{conn: conn, user: user} do
+    body = %{
+      space: %{title: "foobar", cover_image_url: "http://example.com"}
+    } |> Poison.encode!
+
     conn =
       conn
-      |> post(v1_space_path(conn, :create), space: %{title: "foobar", cover_image_url: "http://example.com"})
+      |> post(v1_space_path(conn, :create), body)
       |> doc
 
     assert json_response(conn, 201)["data"]["id"]
```

then `body_params` does have values. It seems the params should be an binary according to this: https://github.com/phoenixframework/phoenix/blob/v1.2.0-rc.1/lib/phoenix/test/conn_test.ex#L209

**Comment by lasseebert** [comment]
I experience the same thing. I'm currently POSTing a `Map` which yields this in the generated docs:

```
* __Request body:__
\```json
{
  "aspect": "body_params"
}
\```
```

If I encode it as JSON and add a `"Content-Type: application/json"` to the request it gives the expected result:

```
* __Request body:__
\```json
{
  "data": {
    "type": "accounts",
    "attributes": {
      "role": "admin",
      "name": "Admin Adminson"
    }
  }
}
\```
```

I basically changed this:

```elixir
    params = %{
      data: %{
        type: "accounts",
        attributes: %{
          name: "Admin Adminson",
          role: "admin"
        }
      }
    }

    conn = build_conn
            |> post("/accounts", params)
            |> doc
```

To this:

```elixir
    params = %{
      data: %{
        type: "accounts",
        attributes: %{
          name: "Admin Adminson",
          role: "admin"
        }
      }
    }
    |> Poison.encode!

    conn = build_conn
            |> put_req_header("content-type", "application/json")
            |> post("/accounts", params)
            |> doc
```

Is this expected?

**Comment by OpakAlex** [comment]
I think it's more phoenix question, then this lib.

**Comment by lasseebert** [comment]
Ok. I have solved the issue for now with a helper function that does the above thing ;)

**Comment by OpakAlex** [comment]
good!
