### ISSUE TITLE
API docs not generated anymore after upgrade to elixir 1.12.2 and Erlang/OTP 24 from Elixir 1.11.2 & Erlang/OTP 23

### ISSUE THREAD

**Issue by MuriukiPM** [api-hogs/bureaucrat#71]
# Environment
OS: Ubuntu Linux (20.04 LTS)
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

Elixir 1.12.2 (compiled with Erlang/OTP 22)

# Configuration
`mix.exs`
```elixir
...
  defp deps do
    [
    ...
   {:jason, "~> 1.0"},
   {:bureaucrat, "~> 0.2.7"},
    ...
    ]
...
```
`test_helper.exs`
```elixir
Bureaucrat.start(
  default_path: "docs/api/README.md",
  paths: [],
  titles: [
    {FooBarWeb.FooController, "/api/foo"},
    {FooBarWeb.BarController, "/api/bar"}
  ],
  env_var: "DOC",
  json_library: Jason
)
ExUnit.start(formatters: [ExUnit.CLIFormatter, Bureaucrat.Formatter], exclude: [:skip])
Ecto.Adapters.SQL.Sandbox.mode(TransactionServer.Repo, :manual)
```

# Current behaviour
 `DOC=1 mix test` has no effect on the documentation generated prior to the upgrade to Elixir 1.12.2 and Erlang/OTP 24 from Elixir 1.11.2 & Erlang/OTP 23

# Expected behaviour
On running `DOC=1 mix test` , the documentation for the API calls should be updated where changes have been made.

**Comment by davidegriffon** [comment]
This issue was resolved in this commit: https://github.com/api-hogs/bureaucrat/commit/0bc5b1fe883077f5e5aaedd5ab3a9eb2a95728c1
The latest version on Hex is quite old, for now you should use `{:bureaucrat, git: "https://github.com/api-hogs/bureaucrat.git", only: [:dev, :test]}`

**Comment by MuriukiPM** [comment]
Thanks @davidegriffon . Tested using both `MarkdownWriter` and `SwaggerSlateMarkdownWriter` and it works with that version.

**Comment by OpakAlex** [comment]
i will release it guys.

**Comment by rafaeelaudibert** [comment]
Awesome, thanks @OpakAlex!

If you could ping me when this has been released to Hex, I'll be glad.

Have a nice weekend

**Comment by severian1778** [comment]
seems like bureaucrat swagger slate markdown as absolutely broken.   All I get is blank api now.

**Comment by OpakAlex** [comment]
yes @rafaeelaudibert @severian1778 i am looking, even release is broken, i can not release new version.

**Comment by OpakAlex** [comment]
release done.
