### ISSUE TITLE
Swagger Integration

### ISSUE THREAD

**Issue by mbuhot** [api-hogs/bureaucrat#9]
As part of a custom markdown writer for bureaucrat, I've extracted descriptions, parameters and response schemas from a [swagger](http://swagger.io) file.
It works similarly to the [swagger2markup](https://github.com/Swagger2Markup/swagger2markup) project.
Is this a feature worth integrating into the bureaucrat library?
My initial implementation is currently tied to my markdown writer module, but it feels like a cross-cutting feature that could benefit any output formatter.

**Comment by OpakAlex** [comment]
@romankuznietsov can you check?

**Comment by kirillplatonov** [comment]
I think it will be amazing feature. It's very handy to use swagger as API documentation. I used it for a long time with ruby's grape gem. If you need some help - let me know, I will be glad to help.

**Comment by romankuznietsov** [comment]
@mbuhot This feature will definitely be useful. It would be great if you submit your implementation as a PR. Thanks in advance!

**Comment by mbuhot** [comment]
@romankuznietsov #10 has the implementation of the custom markdown writer.
It's a bit tricky to demonstrate without an accompanying test phoenix project for bureaucrat, but you can see the [swagger file](https://gist.github.com/mbuhot/bdc13d96accea92d68514ea2193d1f42) and [markdown output](https://gist.github.com/mbuhot/ae1c182c4de4897e910bd6b1e942e626).

**Comment by mbuhot** [comment]
Thanks to @OpakAlex for reviewing the PR.
With that as a starting point, is it in line with how you want to integrate swagger with bureaucrat?

@kirillplatonov: If you have a swagger spec for an existing phoenix app, you could try it out against the SwaggerSlateMarkdownFormatter to see if it works with it.
I've also been working on improving [phoenix_swagger](https://github.com/everydayhero/phoenix_swagger) to generate swagger from a DSL in controller modules.
