### ISSUE TITLE
supporting doc from functions

### ISSUE THREAD

**Issue by sasa1977** [api-hogs/bureaucrat#96]
Currently the `doc` macro must be invoked directly from the test. If it is invoked from a function, a compile-time exception is raised. As a result, we're facing a dilemma: either avoid wrappers, which can lead to excessively noisy code, or avoid generating documentation.

I think it's possible to do better, and allow devs to wrap the requests and still generate the docs. Here's the proposed approach:

1. At compile time, use `nil` for the description if the immediate caller is not test
2. At runtime, if the description is `nil`, try to deduce it from the runtime stack trace using `Process.info(self(), :current_stacktrace)`.
3. If the description can't be found, don't generate the doc (i.e. automatically fallback to `_undocumented`), but emit a warning.

In most cases this should work automagically. In exceptional cases, e.g. making a request from a setup block, it would still work while emitting a warning. The fix in such cases could be switching to `_undocumented` or explicitly passing the description.

WDYT?

**Comment by OpakAlex** [comment]
@sasa1977 create a PR, then we can see ;)
